package com.adhs.logbook.shared

/** English message keys with German translations, shared with native clients. */
object TextCatalog {
    private val german = mapOf(
        "Unit" to "Einheit",
        "Measurements" to "Messwerte",
        "Blood pressure" to "Blutdruck",
        "Pulse" to "Puls",
        "Weight" to "Gewicht",
        "Systolic (mmHg)" to "Systolisch (mmHg)",
        "Diastolic (mmHg)" to "Diastolisch (mmHg)",
        "Pulse (bpm)" to "Puls (bpm)",
        "Weight value" to "Gewichtswert",
        "Show converted value" to "Umgerechneten Wert anzeigen",
        "The entered value and unit are retained. Conversion is display only." to "Eingegebener Wert und Einheit bleiben erhalten. Die Umrechnung dient nur der Anzeige.",
        "Measured at" to "Gemessen am",
        "Manual records only. No clinical interpretation is provided." to "Nur manuelle Aufzeichnungen. Es erfolgt keine medizinische Bewertung.",
        "Add measurement" to "Messwert hinzufügen",
        "Available in observations. Disabling keeps saved records." to "Unter Beobachtungen verfügbar. Gespeicherte Werte bleiben beim Deaktivieren erhalten.",
        "Weekly overview" to "Wochenübersicht",
        "Previous week" to "Vorige Woche",
        "Next week" to "Nächste Woche",
        "Choose week" to "Woche auswählen",
        "Observation distributions" to "Verteilung der Beobachtungen",
        "Legacy dose mood (separate from observations)" to "Stimmung bei Dosiseinträgen (getrennt von Beobachtungen)",
        "No records. Status unknown." to "Keine Aufzeichnungen. Status unbekannt.",
        "Recorded measurements: %d" to "Erfasste Messwerte: %d",
        "Days with measurements: %d / %d" to "Tage mit Messwerten: %d / %d",
        "Quick access" to "Schnellzugriff",
        "Enable quick access" to "Schnellzugriff aktivieren",
        "Review medication" to "Medikament prüfen",
        "Quick access is unavailable. Open Settings to configure it." to "Schnellzugriff ist nicht verfügbar. Richte ihn in den Einstellungen ein.",
        "Medication settings changed. Review the current amount." to "Medikamenteneinstellungen wurden geändert. Prüfe die aktuelle Menge.",
        "Shortcuts open review. Opening a link never saves a dose." to "Kurzbefehle öffnen die Eingabemaske. Das Öffnen eines Links speichert keine Dosis.",
        "Hold the app icon for Log dose. Add the tile from Quick Settings edit mode." to "Halte das App-Symbol für Dosis erfassen gedrückt. Füge die Kachel beim Bearbeiten der Schnelleinstellungen hinzu.",
        "Add Quick Settings tile" to "Schnelleinstellungskachel hinzufügen",
        "Optional medication shortcut" to "Optionaler Medikamenten-Kurzbefehl",
        "Create review shortcut" to "Prüf-Kurzbefehl erstellen",
        "Public labels stay generic. Changes to medication settings require review." to "Öffentliche Beschriftungen bleiben allgemein. Geänderte Medikamenteneinstellungen müssen geprüft werden.",
        "In Shortcuts, add Open dose editor. Leave the shortcut empty for generic review, or choose Configured medication after setup here." to "Füge in Kurzbefehle die Aktion Dosiseingabe öffnen hinzu. Lass die Auswahl für eine allgemeine Eingabe leer oder wähle nach der Einrichtung hier Eingerichtetes Medikament.",
        "Review shortcut configured." to "Prüf-Kurzbefehl eingerichtet.",
        "Add ADHS Logbook from the Lock Screen widget gallery. It opens review after unlocking." to "Füge ADHS Logbook aus der Widget-Galerie des Sperrbildschirms hinzu. Nach dem Entsperren öffnet sich die Eingabemaske.",
        "Show last-log timestamp on Lock Screen" to "Zeitpunkt des letzten Eintrags auf dem Sperrbildschirm anzeigen",
        "Off by default. App lock always hides the timestamp." to "Standardmäßig aus. Die App-Sperre blendet den Zeitpunkt immer aus.",

        "Supply notifications" to "Vorratsbenachrichtigungen",
        "After restore, notifications stay off until you enable them here." to "Nach der Wiederherstellung bleiben Benachrichtigungen aus, bis du sie hier aktivierst.",
        "App lock" to "App-Sperre",
        "Logbook locked" to "Protokoll gesperrt",
        "Unlock logbook" to "Protokoll entsperren",
        "Set a device screen lock first." to "Richte zuerst eine Gerätesperre ein.",
        "Relocks when you leave the app. Exported files remain outside this lock; this is not whole-database encryption." to "Sperrt beim Verlassen der App erneut. Exportierte Dateien werden dadurch nicht geschützt. Dies verschlüsselt nicht die gesamte Datenbank.",
        "Medication log" to "Medikamentenprotokoll",
        "Open logbook" to "Protokoll öffnen",
        "Widget changed. Review the medication and amount in the app." to "Widget geändert. Prüfe Medikament und Menge in der App.",
        "Home-screen widget" to "Startbildschirm-Widget",
        "Generic widget content" to "Neutrale Widget-Anzeige",
        "App lock always hides widget details. Changed medication settings require review in the app." to "Die App-Sperre verbirgt Widget-Details immer. Geänderte Medikamenteneinstellungen müssen in der App geprüft werden.",
        "Widget configured. Add it from your home screen's widget gallery if needed." to "Widget eingerichtet. Füge es bei Bedarf über die Widget-Auswahl des Startbildschirms hinzu.",
        "Save widget configuration" to "Widget-Einstellungen speichern",
        "Widget sharing is unavailable in this build." to "Widget-Datenfreigabe ist in dieser App-Version nicht verfügbar.",
        "Optional features" to "Optionale Funktionen",
        "Optional observations" to "Optionale Beobachtungen",
        "Observations" to "Beobachtungen",
        "Observations & non-use" to "Beobachtungen und Nichteinnahme",
        "Add observation" to "Beobachtung hinzufügen",
        "Edit observation" to "Beobachtung bearbeiten",
        "Focus / everyday functioning" to "Fokus / Alltag",
        "Appetite" to "Appetit",
        "Sleep" to "Schlaf",
        "Symptom / suspected side effect" to "Symptom / vermutete Nebenwirkung",
        "User-noticed benefit" to "Selbst bemerkte Wirkung",
        "User-noticed fading" to "Selbst bemerktes Nachlassen",
        "Category" to "Kategorie",
        "Response" to "Antwort",
        "Choose a response" to "Antwort wählen",
        "Rating" to "Bewertung",
        "None" to "Keine",
        "Unsure" to "Unsicher",
        "Recorded time" to "Erfasster Zeitpunkt",
        "0 = very low · 4 = very high" to "0 = sehr niedrig · 4 = sehr hoch",
        "Observation time" to "Zeitpunkt der Beobachtung",
        "Night starting on (YYYY-MM-DD)" to "Nacht ab (JJJJ-MM-TT)",
        "Optional dose link" to "Optionaler Bezug zu einer Dosis",
        "No dose link" to "Kein Dosisbezug",
        "A link records your context, not medication causation." to "Ein Bezug erfasst den Zusammenhang deiner Notiz. Er belegt keine Medikamentenursache.",
        "No records yet. Unrecorded days remain unknown." to "Noch keine Aufzeichnungen. Tage ohne Aufzeichnung bleiben unbekannt.",
        "Record not taken" to "Nichteinnahme erfassen",
        "Not taken" to "Nicht eingenommen",
        "Only record what you know. Pausing reminders does not record non-use." to "Erfasse nur, was du weißt. Pausierte Erinnerungen erfassen keine Nichteinnahme.",
        "Record a period" to "Zeitraum erfassen",
        "End" to "Ende",
        "A dose is recorded in this non-use period. Correct one record first." to "In diesem Zeitraum ist eine Dosis erfasst. Korrigiere zuerst eine der Aufzeichnungen.",
        "A non-use record overlaps this dose. Correct one record first." to "Eine Nichteinnahme überschneidet sich mit dieser Dosis. Korrigiere zuerst eine Aufzeichnung.",
        "Non-use periods overlap." to "Zeiträume der Nichteinnahme überschneiden sich.",
        "Delete record" to "Aufzeichnung löschen",
        "Delete record?" to "Aufzeichnung löschen?",
        "This cannot be undone." to "Dies kann nicht rückgängig gemacht werden.",
        "Pause reminders" to "Erinnerungen pausieren",
        "Resume / change pause" to "Fortsetzen / Pause ändern",
        "This pauses notifications only. It does not record medication use or non-use." to "Dies pausiert nur Benachrichtigungen. Es erfasst weder Einnahme noch Nichteinnahme.",
        "Resume at a chosen time" to "Zu gewähltem Zeitpunkt fortsetzen",
        "Resume at" to "Fortsetzen am",
        "Supply" to "Vorrat",
        "Supply reminders" to "Vorratserinnerungen",
        "Supply reminder" to "Vorratserinnerung",
        "Your selected prescription request date has arrived." to "Dein gewählter Termin zur Rezeptanfrage ist erreicht.",
        "Review your estimated supply in the app." to "Prüfe deinen geschätzten Vorrat in der App.",
        "Estimated remaining: %s %s" to "Geschätzt verbleibend: %s %s",
        "Count may be incomplete. Review uncounted logs or recount." to "Die Zählung ist möglicherweise unvollständig. Prüfe unberücksichtigte Einträge oder zähle neu.",
        "Restock units" to "Hinzugefügte Einheiten",
        "Add restock" to "Vorrat ergänzen",
        "Use a physical count. Package units are separate from the logged dose." to "Zähle deinen tatsächlichen Vorrat. Packungseinheiten sind von der erfassten Dosis getrennt.",
        "Package unit label" to "Bezeichnung der Packungseinheit",
        "Counted stock now" to "Jetzt gezählter Vorrat",
        "Low-stock threshold" to "Grenze für niedrigen Vorrat",
        "Dose amount per package unit (optional)" to "Dosis je Packungseinheit (optional)",
        "Mapping uses the medication's logging unit. Leave blank to record stock units explicitly in each dose. No conversion is inferred." to "Die Zuordnung nutzt die Dosiseinheit des Medikaments. Leer lassen, um Vorratseinheiten je Dosis selbst anzugeben. Keine Umrechnung wird angenommen.",
        "Prescription request reminder" to "Erinnerung zur Rezeptanfrage",
        "Prescription request date" to "Termin zur Rezeptanfrage",
        "Save count and settings" to "Zählung und Einstellungen speichern",
        "Stock units used (optional)" to "Verbrauchte Vorratseinheiten (optional)",
        "Only for supply tracking; separate from dose amount." to "Nur zur Vorratszählung, getrennt von der Dosis.",
        "Enter zero or a positive stock amount." to "Gib null oder eine positive Vorratsmenge ein.",
        "Summary with details" to "Zusammenfassung mit Details",
        "Include free-text notes" to "Freitextnotizen einschließen",
        "Questions for my appointment" to "Fragen für meinen Termin",
        "Recorded doses: %d" to "Erfasste Dosen: %d",
        "Days with dose records: %d / %d" to "Tage mit Dosiseinträgen: %d / %d",
        "Days with observations: %d / %d" to "Tage mit Beobachtungen: %d / %d",
        "Days with explicit non-use records: %d / %d" to "Tage mit ausdrücklich erfasster Nichteinnahme: %d / %d",
        "Days without records: %d / %d" to "Tage ohne Aufzeichnungen: %d / %d",
        "Missing records are unknown, not confirmed non-use. Counts do not measure adherence or causation." to "Fehlende Aufzeichnungen bedeuten unbekannten Status, keine bestätigte Nichteinnahme. Die Zählung bewertet weder Therapietreue noch Ursachen.",
        "%d recorded doses; total %s %s" to "%d erfasste Dosen; insgesamt %s %s",
        "%d records: %d rated, %d none, %d unsure, %d recorded times" to "%d Aufzeichnungen: %d bewertet, %d keine, %d unsicher, %d Zeitpunkte",
        "Scheduled through %s. Open the app regularly to refresh reminders." to "Geplant bis %s. Öffne die App regelmäßig, um Erinnerungen zu erneuern.",
        "Could not save or load data. Please try again." to "Daten konnten nicht gespeichert oder geladen werden. Versuche es erneut.",
        "Log now" to "Jetzt erfassen", "Snooze 10 min" to "In 10 Min. erinnern", "Open" to "Öffnen",
        "A moment for your log" to "Zeit für dein Logbuch", "Add an entry when you are ready." to "Erfasse einen Eintrag, wenn du bereit bist.",
        "This reminder expired. Open your log to review." to "Diese Erinnerung ist abgelaufen. Öffne dein Logbuch.",
        "From" to "Von", "To" to "Bis",
        "Home" to "Start",
        "History" to "Verlauf",
        "Export" to "Export",
        "Settings" to "Einstellungen",
        "Today" to "Heute",
        "Yesterday" to "Gestern",
        "Get started" to "Los geht’s",
        "A little clarity,\nevery day." to "Ein wenig Klarheit,\njeden Tag.",
        "Log your medication. Keep notes when you want to." to "Erfasse deine Medikamente. Notizen sind freiwillig.",
        "Private. Stored on this device." to "Privat. Auf diesem Gerät gespeichert.",
        "Add your medication" to "Medikament hinzufügen",
        "Edit medication" to "Medikament bearbeiten",
        "Custom medication" to "Eigenes Medikament",
        "Methylphenidate IR" to "Methylphenidat unretardiert",
        "Methylphenidate ER (Concerta-type)" to "Methylphenidat retardiert (Concerta-Typ)",
        "Elvanse / Vyvanse" to "Elvanse / Vyvanse",
        "Atomoxetine / Strattera" to "Atomoxetin / Strattera",
        "Medication name" to "Name des Medikaments",
        "Formulation (optional)" to "Darreichungsform (optional)",
        "Strength with unit (optional)" to "Stärke mit Einheit (optional)",
        "For your records only; no dose conversion." to "Nur zur Dokumentation; keine Dosisumrechnung.",
        "Your usual dose (%s)" to "Deine übliche Dosis (%s)",
        "Enter a positive dose." to "Gib eine positive Dosis ein.",
        "Enter your prescribed dose. You can add another medication later." to "Gib deine verordnete Dosis ein. Weitere Medikamente kannst du später hinzufügen.",
        "Logging is available. No supported estimate is available for this formulation." to "Du kannst Einnahmen erfassen. Für diese Darreichungsform ist keine Schätzung verfügbar.",
        "Saving…" to "Wird gespeichert…",
        "Start" to "Starten",
        "Save medication" to "Medikament speichern",
        "Your log starts here." to "Hier beginnt dein Logbuch.",
        "Add a medication to start your log." to "Füge ein Medikament hinzu, um zu beginnen.",
        "Add medication" to "Medikament hinzufügen",
        "Last logged" to "Zuletzt erfasst",
        "Just now" to "Gerade eben",
        "%d min ago" to "Vor %d Min.",
        "%d h %d min ago" to "Vor %d Std. %d Min.",
        "No dose logged today." to "Heute keine Dosis erfasst.",
        "Estimated level" to "Geschätzter Verlauf",
        "Estimate unavailable" to "Schätzung nicht verfügbar",
        "No doses logged" to "Keine Dosen erfasst",
        "Recently logged" to "Gerade erfasst",
        "Low estimated level" to "Niedriger Schätzwert",
        "Near estimated peak" to "Nahe dem geschätzten Maximum",
        "Estimate increasing" to "Schätzwert steigt",
        "Estimate decreasing" to "Schätzwert sinkt",
        "Your doses are recorded. A short-term curve is not available for this medication." to "Deine Dosen werden erfasst. Für dieses Medikament ist keine kurzfristige Kurve verfügbar.",
        "Log a dose to see your estimate." to "Erfasse eine Dosis, um eine Schätzung zu sehen.",
        "Rough relative estimate, not a medical measurement. Do not use it to decide when to take a dose." to "Grobe relative Schätzung, keine medizinische Messung. Nutze sie nicht zur Entscheidung über den Einnahmezeitpunkt.",
        "About this estimate" to "Über diese Schätzung",
        "＋ Log dose" to "＋ Dosis erfassen",
        "Log now · %s %s" to "Jetzt erfassen · %s %s",
        "Got it" to "Verstanden",
        "A simplified curve uses typical peak times and half-lives from product labels. It is not a validated prediction of your blood level, symptom control, or safe dosing." to "Die vereinfachte Kurve nutzt typische Zeiten und Halbwertszeiten aus Produktinformationen. Sie ist keine validierte Vorhersage deines Blutspiegels, deiner Symptome oder einer sicheren Dosierung.",
        "Food, metabolism and formulation can change the curve. Concerta-type ER, atomoxetine and custom medications have no supported curve. Charts use relative scales; different medications cannot be compared." to "Nahrung, Stoffwechsel und Darreichungsform können die Kurve verändern. Für Concerta-Retardformen, Atomoxetin und eigene Medikamente ist keine Kurve verfügbar. Relative Skalen erlauben keinen Medikamentenvergleich.",
        "Sources: DailyMed Ritalin, Ritalin LA (IR comparison) and Vyvanse capsule labels. Models: ritalin-ir-v1 / vyvanse-capsule-v1. Engine: relative-heuristic-v1." to "Quellen: DailyMed-Fachinformationen zu Ritalin, Ritalin LA (IR-Vergleich) und Vyvanse-Kapseln. Modelle: ritalin-ir-v1 / vyvanse-capsule-v1. Berechnung: relative-heuristic-v1.",
        "Relative estimate for the last 24 hours. %s. Rightmost point: now." to "Relative Schätzung der letzten 24 Stunden. %s. Rechts: jetzt.",
        "Now" to "Jetzt",
        "Dots along the baseline mark logged doses." to "Punkte an der Grundlinie markieren erfasste Dosen.",
        "Log dose" to "Dosis erfassen",
        "Edit entry" to "Eintrag bearbeiten",
        "Choose medication" to "Medikament wählen",
        "Dose (%s)" to "Dosis (%s)",
        "Taken now" to "Jetzt eingenommen",
        "Time zone: %s" to "Zeitzone: %s",
        "How are you feeling?" to "Wie geht es dir?",
        "Optional" to "Optional",
        "Very low" to "Sehr schlecht",
        "Low" to "Schlecht",
        "Okay" to "Okay",
        "Good" to "Gut",
        "Very good" to "Sehr gut",
        ", selected" to ", ausgewählt",
        "Notes (optional)" to "Notizen (optional)",
        "Save dose" to "Dosis speichern",
        "Save changes" to "Änderungen speichern",
        "Choose a medication." to "Wähle ein Medikament.",
        "That time does not exist because the clocks changed. Choose another time." to "Diese Uhrzeit existiert wegen der Zeitumstellung nicht. Wähle eine andere Uhrzeit.",
        "Choose a time now or in the past." to "Wähle jetzt oder einen Zeitpunkt in der Vergangenheit.",
        "Delete entry" to "Eintrag löschen",
        "Delete this entry?" to "Diesen Eintrag löschen?",
        "This removes the dose and its notes from your log. This cannot be undone." to "Damit löschst du die Dosis und ihre Notizen endgültig aus deinem Logbuch.",
        "Delete" to "Löschen",
        "Keep entry" to "Eintrag behalten",
        "Choose day" to "Tag wählen",
        "Show all" to "Alle anzeigen",
        "No doses logged yet." to "Noch keine Dosen erfasst.",
        "No doses logged for this day." to "An diesem Tag keine Dosen erfasst.",
        "Times displayed in %s." to "Zeiten werden in %s angezeigt.",
        "Share with\nyour doctor" to "Für dein\nArztgespräch",
        "A clear record of your medication and how you felt." to "Eine Übersicht deiner Medikamente und deines Befindens.",
        "From · %s" to "Von · %s",
        "To · %s" to "Bis · %s",
        "Last 7 days" to "Letzte 7 Tage",
        "Last 30 days" to "Letzte 30 Tage",
        "PDF report" to "PDF-Bericht",
        "Graphs, doses, mood & notes" to "Kurven, Dosen, Stimmung und Notizen",
        "Open in a spreadsheet" to "In einer Tabelle öffnen",
        "Choose a valid range of up to 366 days." to "Wähle einen gültigen Zeitraum mit höchstens 366 Tagen.",
        "No entries in this date range." to "Keine Einträge in diesem Zeitraum.",
        "Entries: %d · %s" to "Einträge: %d · %s",
        "Only your selected dates are included. You choose where to share the file." to "Nur der gewählte Zeitraum wird exportiert. Du entscheidest, wohin die Datei geht.",
        "Preparing report…" to "Bericht wird erstellt…",
        "Export report" to "Bericht exportieren",
        "Could not export this report. Please try again." to "Der Bericht konnte nicht exportiert werden. Versuche es erneut.",
        "Medications" to "Medikamente",
        "Usual dose · %s %s" to "Übliche Dosis · %s %s",
        "Edit %s" to "%s bearbeiten",
        "Remove %s" to "%s entfernen",
        "＋ Add medication" to "＋ Medikament hinzufügen",
        "Reminders" to "Erinnerungen",
        "A gentle reminder to log. Delivery may be delayed by battery settings." to "Eine sanfte Erinnerung ans Erfassen. Akkueinstellungen können die Zustellung verzögern.",
        "Reminder options" to "Erinnerungsoptionen",
        "Remove reminder" to "Erinnerung entfernen",
        "＋ Add time" to "＋ Uhrzeit hinzufügen",
        "Notifications are turned off. Your reminder times are saved." to "Mitteilungen sind ausgeschaltet. Deine Erinnerungszeiten sind gespeichert.",
        "Open notification settings" to "Mitteilungseinstellungen öffnen",
        "Data & privacy" to "Daten und Datenschutz",
        "Your log stays on this device. No account needed." to "Dein Logbuch bleibt auf diesem Gerät. Kein Konto nötig.",
        "Cloud backups are disabled. Uninstalling removes your log. Create a backup to restore it later." to "Cloud-Backups sind deaktiviert. Beim Deinstallieren wird dein Logbuch gelöscht. Erstelle eine Sicherung zur späteren Wiederherstellung.",
        "Export your log →" to "Logbuch exportieren →",
        "ADHS Logbook · 0.4.0\nEstimates are informational and are not medical measurements." to "ADHS Logbook · 0.4.0\nSchätzungen dienen der Information und sind keine medizinischen Messungen.",
        "Remove medication?" to "Medikament entfernen?",
        "%s will no longer appear for new doses. Past entries remain in your history." to "%s wird nicht mehr für neue Dosen angeboten. Vergangene Einträge bleiben im Verlauf.",
        "Remove" to "Entfernen",
        "Keep" to "Behalten",
        "Dose logged" to "Dosis erfasst",
        "Undo" to "Rückgängig",
        "Changes saved" to "Änderungen gespeichert",
        "Entry deleted" to "Eintrag gelöscht",
        "Something went wrong" to "Etwas ist schiefgegangen",
        "Close" to "Schließen",
        "Back" to "Zurück",
        "Choose a medication to enable log-now. Otherwise this reminder opens your log." to "Wähle ein Medikament für das direkte Erfassen. Ohne Auswahl öffnet die Erinnerung dein Logbuch.",
        "Generic reminder" to "Allgemeine Erinnerung",
        "One follow-up after 30 minutes" to "Einmal nach 30 Minuten erinnern",
        "Stop this reminder after" to "Diese Erinnerung beenden nach",
        "%d minutes" to "%d Minuten",
        "Snooze adds 10 minutes, up to the cutoff. Reminder text hides medication names." to "Erneute Erinnerung nach 10 Minuten, höchstens bis zum Ende. Der Mitteilungstext verbirgt Medikamentennamen.",
        "Save" to "Speichern",
        "Cancel" to "Abbrechen",
        "Backup created." to "Sicherung erstellt.",
        "Backup failed. The selected file may be incomplete; create a new backup." to "Sicherung fehlgeschlagen. Die gewählte Datei ist möglicherweise unvollständig. Erstelle eine neue Sicherung.",
        "Cannot open backup. Check the passphrase and file. Your log was not changed." to "Sicherung kann nicht geöffnet werden. Prüfe Passwort und Datei. Dein Logbuch wurde nicht geändert.",
        "Last backup: %s" to "Letzte Sicherung: %s",
        "Create backup" to "Sicherung erstellen",
        "Restore backup" to "Sicherung wiederherstellen",
        "No pre-restore snapshot available." to "Keine vorherige Sicherung auf diesem Gerät verfügbar.",
        "Recover pre-restore log" to "Logbuch vor Wiederherstellung zurückholen",
        "Working…" to "Wird verarbeitet…",
        "Encrypted backup. Use at least 10 characters. Keep the passphrase separately; it cannot be recovered." to "Verschlüsselte Sicherung. Verwende mindestens 10 Zeichen. Bewahre das Passwort separat auf; es kann nicht wiederhergestellt werden.",
        "You choose the file destination. Cloud-backed file providers are outside this app's local storage." to "Du wählst den Speicherort. Cloud-Dateianbieter liegen außerhalb des lokalen Speichers dieser App.",
        "Passphrase" to "Passwort",
        "Repeat passphrase" to "Passwort wiederholen",
        "Choose file" to "Datei wählen",
        "No entries" to "Keine Einträge",
        "Replace current log?" to "Aktuelles Logbuch ersetzen?",
        "Medications: %d · Entries: %d" to "Medikamente: %d · Einträge: %d",
        "This replaces the current log. A private pre-restore snapshot is kept on this device. Reminders stay off until you enable them." to "Das aktuelle Logbuch wird ersetzt. Eine private Kopie des vorherigen Logbuchs bleibt auf diesem Gerät. Erinnerungen bleiben aus, bis du sie aktivierst.",
        "Backup restored. Reminders are off." to "Sicherung wiederhergestellt. Erinnerungen sind ausgeschaltet.",
        "Replace log" to "Logbuch ersetzen",
        "unit" to "Einheit",
        "ADHS Logbook — Medication log" to "ADHS Logbook — Medikamentenprotokoll",
        "%s to %s | %s" to "%s bis %s | %s",
        "Generated %s | Model: relative-heuristic-v1" to "Erstellt am %s | Modell: relative-heuristic-v1",
        "Rough relative estimates, not measured blood levels or dosing guidance." to "Grobe relative Schätzungen, keine Blutmessung oder Dosierungsanleitung.",
        "Curves are scaled separately. They cannot compare medications or days." to "Kurven sind separat skaliert. Medikamente und Tage sind nicht vergleichbar.",
        "Private health record · Page %d" to "Privates Gesundheitsprotokoll · Seite %d",
        "No doses logged. This does not confirm that no medication was taken." to "Keine Dosen erfasst. Das bestätigt nicht, dass kein Medikament eingenommen wurde.",
        "Estimate unavailable. Logged doses are shown below." to "Schätzung nicht verfügbar. Erfasste Dosen stehen unten.",
        "Start of day" to "Tagesbeginn",
        "End of day" to "Tagesende",
        "Time" to "Uhrzeit",
        "Medication" to "Medikament",
        "Dose" to "Dosis",
        "Mood" to "Stimmung",
        "Note: %s" to "Notiz: %s",
        "Continued notes for entry %d" to "Weitere Notizen zu Eintrag %d",
        "Export medication log" to "Medikamentenprotokoll exportieren"
    )
    fun text(key: String, language: String): String = if(language == "de") german[key] ?: key else key
}
